### ISSUE TITLE
1.0.4: tests/test_integration.py::test_from_str fails

### ISSUE THREAD

**Issue by olebole** [yt-project/cmyt#65]
I am currently [packaging cmyt for Debian](https://bugs.debian.org/1004960), which is a new dependency of yt 4.0.2. When running the tests, I observed the following failure:
```
Error: Image dimensions did not match.
  Expected shape: (374, 917)
    /tmp/tmpz7mck7eo/tests.test_integration.test_from_str_dusk/baseline.png
  Actual shape: (372, 917)
    /tmp/tmpz7mck7eo/tests.test_integration.test_from_str_dusk/result.png
```
This happens with all `test_from_str` and `test_from_obj` tests.

Python: 3.0.10
More-itertools: 8.10.0
Numpy: 1.22.1
Pytest: 6.2.5
Matplotlib: 3.5.1
Pytest-mpl: 0.13
Colorspacious: 1.1.2

**Comment by neutrinoceros** [comment]
Hi @olebole, thanks for reporting this! 

> Python: 3.0.10

I'm sure this is a typo, you must mean 3.10.x ?
Anyway I'm very surprised this is happening, considering cmyt's test run at least once a day with bleeding-edge dependency, it looks like something that we should have seen already.
I'll have a look later today.

**Comment by olebole** [comment]
That was Python 3.9.10.

**Comment by neutrinoceros** [comment]
Couldn't resist a quick test now and I can't reproduce this on my machine with the exact specs you gave.
So now I'm thinking that this is likely a platform-dependent behaviour from matplotlib, and I am not sure that there's anything that I can do to work around it.

**Comment by olebole** [comment]
My platform is Debian x86-64; I didn't mention this (but it is probably obvious).

What is a bit confusing is hat pytest-mpl reports itself version 0.12.dev0:
```
 $ pip3 install pytest-mpl
Defaulting to user installation because normal site-packages is not writeable
WARNING: Ignoring invalid distribution -oad (/home/oles/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -oad (/home/oles/.local/lib/python3.9/site-packages)
Collecting pytest-mpl
  Using cached pytest_mpl-0.13-py3-none-any.whl (13 kB)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from pytest-mpl) (3.5.1)
Requirement already satisfied: pytest in /usr/lib/python3/dist-packages (from pytest-mpl) (6.2.5)
WARNING: Ignoring invalid distribution -oad (/home/oles/.local/lib/python3.9/site-packages)
Installing collected packages: pytest-mpl
WARNING: Ignoring invalid distribution -oad (/home/oles/.local/lib/python3.9/site-packages)
Successfully installed pytest-mpl-0.13
 $ python3 -c "import pytest_mpl; print(pytest_mpl.__version__)"
0.12.dev0
```

Is there a way to find out how the image dimensions of the result are built?

**Comment by olebole** [comment]
Setting `MPLBACKEND` doesn't make a difference. I will open an issue on https://github.com/matplotlib/pytest-mpl so see if they can help.

**Comment by olebole** [comment]
... ahh: checking their [README](https://github.com/matplotlib/pytest-mpl/blob/master/README.rst#package-version-dependencies): matplotlib itself and freetype may create slight differences, and they recommend to pin these versions.

That makes this issue unresolvable. Unfortunately this means that I need to disable these tests in Debian, since I can't rely on specific versions.
